name: Goldold
title: gold with all you need to know about relationship
description: Goldold is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false
paginate: ""
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
  - title: Privacy policy
    url: /Privacy-policy
email: youremail@xyz.com
disqus_username: disqus_username
